export const GenresArr = ["fantasy", "science fiction", "dystopian", "action and adventure", "mystery", "horror", "thriller and suspense", "historical fiction", "romance", "womens fiction", "LGBTQ+", "classics", "contemporary fiction", "plays and screenplays", "poetry", "literary fiction", "magical realism", "comics and graphic novels", "short story", "young adult", "new adult", "childrens literature", "memoir and autobiography", "biography", "food and drink", "art and photography", "self-help", "history", "travel", "true crime", "humor", "essays", "guide how-to", "religion and spirituality", "humanities and social sciences", "parenting and families", "science and technology"]

export const GenresObj = {
    "action and adventure": "Action and Adventure",
    "art and photography": "Art and Photography",
    "biography": "Biography",
    "childrens literature": "Childrens literature",
    "classics": "Classics",
    "comics and graphic novels": "Comics and Graphic Novels",
    "contemporary fiction": "Contemporary Fiction",
    "dystopian": "Dystopian",
    "essays": "Essays",
    "fantasy": "Fantasy",
    "food and drink": "Food and Drink",
    "guide how to": "Guide / How-to",
    "horror": "Horror",
    "historical fiction": "Historical Fiction",
    "history": "History",
    "humanities and social sciences": "Humanities and Social Sciences",
    "humor": "Humor",
    "LGBTQ+": "LGBTQ+",
    "literary fiction": "Literary Fiction",
    "memoir and autobiography": "Memoir and Autobiography",
    "mystery": "Mystery",
    "magical realism": "Magical Realism",
    "new adult": "New Adult",
    "parenting and families": "Parenting and Families",
    "plays and screenplays": "Plays and Screenplays",
    "poetry": "Poetry",
    "religion and spirituality": "Religion and Spirituality",
    "romance": "Romance",
    "science and technology": "Science and Tecnology",
    "science fiction": "Science Fiction",
    "self help": "Self-help",
    "short story": "Short Story",
    "thriller and suspense": "Thriller and Suspense",
    "travel": "Travel",
    "true crime": "True Crime",
    "womens fiction": "Women's Fiction",
    "young adult": "Young Adult",
}